/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jframes;

/**
 *
 * @author enmac
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        MenuCategorias = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        MenuProductos = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        MenuFacturar = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        MenuReportes = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        MenuHistorial = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        MenuLogout = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MenuCategorias.setBackground(new java.awt.Color(162, 210, 255));
        MenuCategorias.setForeground(new java.awt.Color(95, 47, 35));
        MenuCategorias.setText("Categorias");
        MenuCategorias.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        MenuCategorias.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        MenuCategorias.setPreferredSize(new java.awt.Dimension(150, 40));

        jMenuItem2.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        jMenuItem2.setText("Nueva Categoria");
        jMenuItem2.setPreferredSize(new java.awt.Dimension(200, 30));
        MenuCategorias.add(jMenuItem2);

        jMenuItem3.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        jMenuItem3.setText("Gestionar Categorias");
        jMenuItem3.setPreferredSize(new java.awt.Dimension(200, 30));
        MenuCategorias.add(jMenuItem3);

        jMenuBar1.add(MenuCategorias);

        MenuProductos.setBackground(new java.awt.Color(162, 210, 255));
        MenuProductos.setForeground(new java.awt.Color(95, 47, 35));
        MenuProductos.setText("Productos");
        MenuProductos.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        MenuProductos.setPreferredSize(new java.awt.Dimension(150, 40));

        jMenuItem1.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        jMenuItem1.setText("Nuevo Producto");
        jMenuItem1.setPreferredSize(new java.awt.Dimension(200, 30));
        MenuProductos.add(jMenuItem1);

        jMenuItem4.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        jMenuItem4.setText("Gestionar Productos");
        jMenuItem4.setPreferredSize(new java.awt.Dimension(200, 30));
        MenuProductos.add(jMenuItem4);

        jMenuItem5.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        jMenuItem5.setText("Actualizar Stock");
        jMenuItem5.setPreferredSize(new java.awt.Dimension(200, 30));
        MenuProductos.add(jMenuItem5);

        jMenuBar1.add(MenuProductos);

        MenuFacturar.setBackground(new java.awt.Color(162, 210, 255));
        MenuFacturar.setForeground(new java.awt.Color(95, 47, 35));
        MenuFacturar.setText("Facturar");
        MenuFacturar.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        MenuFacturar.setPreferredSize(new java.awt.Dimension(150, 40));

        jMenuItem6.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        jMenuItem6.setText("Nueva Venta");
        jMenuItem6.setPreferredSize(new java.awt.Dimension(200, 30));
        MenuFacturar.add(jMenuItem6);

        jMenuItem7.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        jMenuItem7.setText("Gestionar Ventas");
        jMenuItem7.setPreferredSize(new java.awt.Dimension(200, 30));
        MenuFacturar.add(jMenuItem7);

        jMenuBar1.add(MenuFacturar);

        MenuReportes.setBackground(new java.awt.Color(162, 210, 255));
        MenuReportes.setForeground(new java.awt.Color(95, 47, 35));
        MenuReportes.setText("Reportes");
        MenuReportes.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        MenuReportes.setPreferredSize(new java.awt.Dimension(150, 40));

        jMenuItem8.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        jMenuItem8.setText("Reportes Categorias");
        jMenuItem8.setPreferredSize(new java.awt.Dimension(200, 30));
        MenuReportes.add(jMenuItem8);

        jMenuItem9.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        jMenuItem9.setText("Reportes Productos");
        jMenuItem9.setPreferredSize(new java.awt.Dimension(200, 30));
        MenuReportes.add(jMenuItem9);

        jMenuItem11.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        jMenuItem11.setText("Reportes Ventas");
        jMenuItem11.setPreferredSize(new java.awt.Dimension(200, 30));
        MenuReportes.add(jMenuItem11);

        jMenuBar1.add(MenuReportes);

        MenuHistorial.setBackground(new java.awt.Color(162, 210, 255));
        MenuHistorial.setForeground(new java.awt.Color(95, 47, 35));
        MenuHistorial.setText("Historial");
        MenuHistorial.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        MenuHistorial.setPreferredSize(new java.awt.Dimension(150, 40));

        jMenuItem10.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        jMenuItem10.setText("Ver Historial");
        jMenuItem10.setPreferredSize(new java.awt.Dimension(200, 30));
        MenuHistorial.add(jMenuItem10);

        jMenuBar1.add(MenuHistorial);

        MenuLogout.setBackground(new java.awt.Color(162, 210, 255));
        MenuLogout.setForeground(new java.awt.Color(95, 47, 35));
        MenuLogout.setText("Cerrar Sesion");
        MenuLogout.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        MenuLogout.setPreferredSize(new java.awt.Dimension(150, 40));
        jMenuBar1.add(MenuLogout);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1200, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 659, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuCategorias;
    private javax.swing.JMenu MenuFacturar;
    private javax.swing.JMenu MenuHistorial;
    private javax.swing.JMenu MenuLogout;
    private javax.swing.JMenu MenuProductos;
    private javax.swing.JMenu MenuReportes;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    // End of variables declaration//GEN-END:variables
}
